
/* Generated by fzmparser version 2.8 --- DO NOT EDIT! */

/* Uses following resources: */
/* 8 events, 5+0 states, 0 inputs, 4 outputs, 6+0 match regs, 0+0 capture regs */

#include "sct_fsm.h"


void sct_fsm_init (void)
{
LPC_SCT->CONFIG = (LPC_SCT->CONFIG & ~0x00060001) | 0x00000001; /* UNIFIED */

/* MATCH/CAPTURE registers */

/* Unified counter - register side L is used and accessed as 32 bit value, reg H is not used */
LPC_SCT->REGMODE_L = 0x00000000;         /* U: 6x MATCH, 0x CAPTURE, 2 unused */

LPC_SCT->MATCH[0].U = entry_mat;             /* entry_match */
LPC_SCT->MATCHREL[0].U = entry_mat;
LPC_SCT->MATCH[1].U = flash;             /* flash_mat0 */
LPC_SCT->MATCHREL[1].U = flash;
LPC_SCT->MATCH[2].U = flash1;             /* flash_mat1 */
LPC_SCT->MATCHREL[2].U = flash1;
LPC_SCT->MATCH[3].U = delay;             /* match0 */
LPC_SCT->MATCHREL[3].U = delay;
LPC_SCT->MATCH[4].U = yel_delay;             /* yel_delay_mat */
LPC_SCT->MATCHREL[4].U = yel_delay;
LPC_SCT->MATCH[5].U = yel_flash;             /* yel_flash_mat */
LPC_SCT->MATCHREL[5].U = yel_flash;

/* OUTPUT registers */
LPC_SCT->OUT[5].SET = 0x00000002;        /* out_track */
LPC_SCT->OUT[5].CLR = 0x00000008;
LPC_SCT->OUT[2].SET = 0x00000009;        /* turn_green */
LPC_SCT->OUT[2].CLR = 0x00000080;
LPC_SCT->OUT[0].SET = 0x00000002;        /* turn_red */
LPC_SCT->OUT[0].CLR = 0x00000041;
LPC_SCT->OUT[1].SET = 0x000000F5;        /* turn_yellow */
LPC_SCT->OUT[1].CLR = 0x0000003A;
  /* Unused outputs must not be affected by any event */
LPC_SCT->OUT[3].SET = 0;
LPC_SCT->OUT[3].CLR = 0;
LPC_SCT->OUT[4].SET = 0;
LPC_SCT->OUT[4].CLR = 0;

/* Conflict resolution register */
LPC_SCT->RES = (LPC_SCT->RES & ~0x0000000C) | 0x0000000C;

/* EVENT registers */
LPC_SCT->EV[0].CTRL = 0x0000D000;     /* U: --> state RED */
LPC_SCT->EV[0].STATE = 0x00000001;
LPC_SCT->EV[1].CTRL = 0x00015003;     /* U: --> state YELLOW */
LPC_SCT->EV[1].STATE = 0x00000002;
LPC_SCT->EV[2].CTRL = 0x00025004;     /* U: --> state YELLOW_FLASH */
LPC_SCT->EV[2].STATE = 0x00000004;
LPC_SCT->EV[3].CTRL = 0x00015003;     /* U: --> state YELLOW */
LPC_SCT->EV[3].STATE = 0x00000008;
LPC_SCT->EV[6].CTRL = 0x0000F165;     /* U: --> state RED */
LPC_SCT->EV[6].STATE = 0x00000010;
LPC_SCT->EV[7].CTRL = 0x0001FD65;     /* U: --> state GREEN */
LPC_SCT->EV[7].STATE = 0x00000010;
LPC_SCT->EV[4].CTRL = 0x00025001;     /* U: --> state YELLOW_FLASH */
LPC_SCT->EV[4].STATE = 0x00000010;
LPC_SCT->EV[5].CTRL = 0x00025002;     /* U: --> state YELLOW_FLASH */
LPC_SCT->EV[5].STATE = 0x00000010;

/* STATE registers */
LPC_SCT->STATE_L = 0;

/* state names assignment: */
  /* State U 0: U_ENTRY */
  /* State U 1: RED */
  /* State U 2: YELLOW */
  /* State U 3: GREEN */
  /* State U 4: YELLOW_FLASH */

/* CORE registers */
LPC_SCT->START_L = 0x00000000;
LPC_SCT->STOP_L =  0x00000000;
LPC_SCT->HALT_L =  0x00000000;
LPC_SCT->LIMIT_L = 0x000000CF;
LPC_SCT->EVEN =    0x00000000;
LPC_SCT->DMAREQ0 = 0x00000000;
LPC_SCT->DMAREQ1 = 0x00000000;

}
