#ifndef __SCT_FSM_H__
#define __SCT_FSM_H__

/* Generated by fzmparser version 2.8 --- DO NOT EDIT! */

#include "sct_user.h"

extern void sct_fsm_init (void);

/* Output assignments (and their defaults if specified) */
#define sct_fsm_OUTPUT_out_track (5)
#define sct_fsm_OUTPUT_turn_green (2)
#define sct_fsm_OUTPUT_turn_red (0)
#define sct_fsm_OUTPUT_turn_yellow (1)

#define sct_fsm_setOutputDefault() do {LPC_SCT->OUTPUT = (LPC_SCT->OUTPUT & ~0x00000000) | 0x00000000;} while(0)


/* Match register reload macro definitions */
#define sct_fsm_reload_entry_match(value) do {LPC_SCT->MATCHREL[0].U = value;} while(0)
#define sct_fsm_reload_flash_mat0(value) do {LPC_SCT->MATCHREL[1].U = value;} while(0)
#define sct_fsm_reload_flash_mat1(value) do {LPC_SCT->MATCHREL[2].U = value;} while(0)
#define sct_fsm_reload_match0(value) do {LPC_SCT->MATCHREL[3].U = value;} while(0)
#define sct_fsm_reload_yel_delay_mat(value) do {LPC_SCT->MATCHREL[4].U = value;} while(0)
#define sct_fsm_reload_yel_flash_mat(value) do {LPC_SCT->MATCHREL[5].U = value;} while(0)

#endif
